fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: python
    hooks:
      - id: clang-format
        args: [--style=WebKit]
      # - id: clang-tidy
      #   args: [-checks=*, -warnings-as-errors=*]
      # - id: oclint
      #   args: [-enable-clang-static-analyzer, -enable-global-analysis]
      # - id: uncrustify
      - id: cppcheck
        args: [--enable=all]